CREATE TABLE IF NOT EXISTS "Records" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" text NOT NULL,
    "ReleaseYear" integer NOT NULL,
    "Genre" text NOT NULL,
    "Artist" text NOT NULL,
    "trackCount" integer NOT NULL,
    "Duration" integer NOT NULL
);