CREATE TABLE IF NOT EXISTS "tracks" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" text NOT NULL,
    "Artist" text NOT NULL,
    "playedAt" timestamp NOT NULL,
    "channel" text NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "ux_tracks_identity_ci"
ON "tracks" (lower("channel"), lower("Artist"), lower("Name"));