CREATE TABLE IF NOT EXISTS "tracks" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" text NOT NULL,
    "Artist" text NOT NULL,
    "playedAt" timestamp NOT NULL,
    "channel" text NOT NULL
);